---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: rakuos-custom
description: This is my personal OS image.

base-image: ghcr.io/rakuos/rakuos-base
image-version: latest 

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: signing
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
  - type: default-flatpaks
    configurations:
      - scope: system
        notify: false
        repo:
          url: https://flathub.org/repo/flathub.flatpakrepo
          title: Flathub (system)
        install:
          - org.chromium.Chromium 